# auto-generated by py -m evennia (__main__.py)
import os
import sys
from evennia.server.evennia_launcher import main
sys.path.insert(0, os.path.abspath(os.getcwd()))
sys.path.insert(0, os.path.join(sys.prefix, "Lib", "site-packages"))
main()
